#import "documents/lib.typ": daftar-hadir-magang

#daftar-hadir-magang(
  nama: "Samuel",
  nim: "2231010010",
  pejabat: (
    (nama: "Prof. Ray Guang Cheng", jabatan: "Dosen Pembimbing", hp: ""),
    (nama: "Ian Joseph Chandra", jabatan: "Mentor Laboratorium", hp: ""),
  ),
  entries: (
    (hari_tanggal: "Jumat, 26 Jun 2026", datang: "09:00", pulang: "17:00", kegiatan: "Diskusi pengalihan Meetily dari aplikasi GUI desktop ke server API/CLI headless; persiapan ruang kerja dan dokumentasi", paraf: ""),
    (hari_tanggal: "Senin, 29 Jun 2026", datang: "09:26", pulang: "17:00", kegiatan: "Inisialisasi repositori ai-meeting-agent; perancangan Fase 1-7 (Axum, CLI, transkripsi, HTTP API, pekerjaan, ringkasan)", paraf: ""),
    (hari_tanggal: "Selasa, 30 Jun 2026", datang: "09:20", pulang: "17:00", kegiatan: "Transkripsi potongan paralel ditambah identifikasi pembicara (sherpa-onnx); jalur rilis CI; dokumentasi OpenAPI", paraf: ""),
    (hari_tanggal: "Rabu, 01 Jul 2026", datang: "09:16", pulang: "17:00", kegiatan: "Deliverable Minggu 1: Dokumen Arsitektur Perangkat Lunak (PlantUML ke PDF Typst), spesifikasi API, persiapan ruang kerja, uji integrasi vLLM", paraf: ""),
    (hari_tanggal: "Kamis, 02 Jul 2026", datang: "-", pulang: "-", kegiatan: "Tidak tersedia - Mengikuti acara Workshop", paraf: ""),
    (hari_tanggal: "Jumat, 03 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Menulis ulang identifikasi pembicara sebagai pipeline speakrs dalam-proses; memperbaiki autentikasi health/version; koleksi Postman", paraf: ""),
    (hari_tanggal: "Senin, 06 Jul 2026", datang: "09:20", pulang: "17:00", kegiatan: "Pipeline pemrosesan audio dalam memori (pipa FFmpeg); prioritas GPU untuk identifikasi pembicara; eksplorasi Snipe-IT", paraf: ""),
    (hari_tanggal: "Selasa, 07 Jul 2026", datang: "09:15", pulang: "17:00", kegiatan: "Dokumen Persyaratan Produk untuk Manajemen Inventaris melalui LLM; studi MCP; laporan AI Agent Meeting", paraf: ""),
    (hari_tanggal: "Rabu, 08 Jul 2026", datang: "09:15", pulang: "17:00", kegiatan: "Penerapan Snipe-IT ke server .117; pembaruan Dokumen Persyaratan Produk AI Meeting Agent; penambahan dukungan format video (MP4/AVI/MOV/MKV)", paraf: ""),
    (hari_tanggal: "Kamis, 09 Jul 2026", datang: "09:15", pulang: "17:00", kegiatan: "Penyelesaian metadata Minggu 2 (ekstraksi info berkas, penguraian nama berkas, logika prioritas) - selesai 100%; refaktor tumpukan Docker; MCP AI Meeting Agent", paraf: ""),
    (hari_tanggal: "Senin, 13 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Debug integrasi server MCP; dukungan GPU khusus platform (CoreML/CUDA); refaktor pipeline identifikasi dan transkripsi pembicara; perbaikan GitHub Actions", paraf: ""),
    (hari_tanggal: "Selasa, 14 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Pemasangan GitHub self-hosted runner; diskusi dengan Prof Riri; penyelesaian masalah pembangunan multi-arsitektur (lembur: 2 jam 47 menit)", paraf: ""),
    (hari_tanggal: "Rabu, 15 Jul 2026", datang: "-", pulang: "-", kegiatan: "Tidak tersedia - Mengikuti Workshop di Groundhog Technologies", paraf: ""),
    (hari_tanggal: "Kamis, 16 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Penerapan Openclaw ke server .117; integrasi AI Meeting Agent dengan Openclaw; pemisahan layanan identifikasi; perbaikan pemuatan GPU (lembur: 5 menit)", paraf: ""),
    (hari_tanggal: "Jumat, 17 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Integrasi Hermes Agent ke Telegram; forking API Telegram; perbaikan masalah berkas besar; penulisan laporan mingguan", paraf: ""),
    (hari_tanggal: "Senin, 20 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Pemindahan API aplikasi Meetily ke API ai-meeting-agent; perbaikan masalah pembangunan; penambahan fitur pekerjaan latar belakang; penulisan panduan Meetily", paraf: ""),
    (hari_tanggal: "Selasa, 21 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Membuat ringkasan dapat diedit di Meetily; memperkaya detail rapat (judul, peserta, lokasi, tanggal); bank suara untuk identifikasi pembicara", paraf: ""),
    (hari_tanggal: "Rabu, 22 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Menjelajahi fitur Snipe-IT (manajemen aset, produsen); rapat mingguan", paraf: ""),
    (hari_tanggal: "Kamis, 23 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Integrasi AI Meeting Agent ke Microsoft Teams; pengembangan bot Teams secara manual (Vexa tidak kompatibel dengan Podman)", paraf: ""),
    (hari_tanggal: "Jumat, 24 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Menjelajahi Snipe-IT; kajian dan perencanaan AI Assisted Paper; memulai pengembangan AI Assisted Research", paraf: ""),
    (hari_tanggal: "Senin, 27 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Penyesuaian Snipe-IT untuk data manajemen properti NTUST; penambahan fungsi pemindai; perbaikan check-out/check-in", paraf: ""),
    (hari_tanggal: "Selasa, 28 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Perbaikan masalah pemindai Snipe-IT; kehadiran Workshop 6G; impor format NTUST; ekspor format NTUST", paraf: ""),
    (hari_tanggal: "Rabu, 29 Jul 2026", datang: "08:40", pulang: "17:00", kegiatan: "Pembuatan label untuk setiap barang di Snipe-IT; pembuatan label komponen dan lisensi; dukungan lokasi bersarang", paraf: ""),
    (hari_tanggal: "Kamis, 30 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Rapat mingguan; perbaikan masalah Snipe-IT; fitur check-out mandiri pengguna", paraf: ""),
    (hari_tanggal: "Jumat, 31 Jul 2026", datang: "09:00", pulang: "17:00", kegiatan: "Fitur konfirmasi check-out (pengguna A memerlukan konfirmasi dari pengguna B); perbaikan masalah penerapan; penyesuaian ke PostgreSQL", paraf: ""),
    (hari_tanggal: "Senin, 03 Agt 2026", datang: "08:40", pulang: "22:35", kegiatan: "Migrasi Snipe-IT dari MySQL ke Postgres; streaming audio melalui HTTP; pengiriman notulen rapat melalui email ke peserta kalender; auto-join Teams", paraf: ""),
    (hari_tanggal: "Selasa, 04 Agt 2026", datang: "08:50", pulang: "17:00", kegiatan: "Google OAuth sepenuhnya di sisi server; penerapan langsung OAuth di server lab; halaman acara kalender; pengerjaan ulang email notulen", paraf: ""),
    (hari_tanggal: "Rabu, 05 Agt 2026", datang: "08:50", pulang: "17:00", kegiatan: "Validasi dan pengujian auto-join bot Meetily; pengujian dan perbaikan bug Snipe-IT; sinkronisasi AI-assisted research ke GitHub", paraf: ""),
    (hari_tanggal: "Kamis, 06 Agt 2026", datang: "09:00", pulang: "23:21", kegiatan: "Rapat pagi (sinkronisasi lab); analisis Labs Inventory.xlsx; revisi pada antarmuka web impor JSON NTUST; impor multi-peminjam", paraf: ""),
    (hari_tanggal: "Jumat, 07 Agt 2026", datang: "09:00", pulang: "17:00", kegiatan: "Penyempurnaan templat Excel inventaris lab; pembuatan kata sandi pengguna massal; riwayat check-out; layanan mandiri pemindai peminjam; perbaikan QR", paraf: ""),
    (hari_tanggal: "Senin, 10 Agt 2026", datang: "09:00", pulang: "17:00", kegiatan: "Persiapan dokumen akhir untuk magang; penambahan dukungan IEEE pada AI Assisted Research; perbaikan bug", paraf: ""),
    (hari_tanggal: "Selasa, 11 Agt 2026", datang: "-", pulang: "-", kegiatan: "Kunjungan Perusahaan ke Systex", paraf: ""),
    (hari_tanggal: "Rabu, 12 Agt 2026", datang: "09:00", pulang: "17:00", kegiatan: "Perbaikan masalah obrolan; perbaikan pencarian kertas LLM; LLM kini dapat memanggil alat untuk pencarian kertas", paraf: ""),
    (hari_tanggal: "Jumat, 13 Agt 2026", datang: "09:00", pulang: "17:00", kegiatan: "Rapat mingguan; penulisan panduan pengguna Snipe-IT; penulisan panduan admin Snipe-IT", paraf: ""),
    (hari_tanggal: "Kamis, 14 Agt 2026", datang: "09:00", pulang: "17:00", kegiatan: "Video testimoni; panduan pengguna untuk AI assisted research; perbaikan masalah", paraf: ""),
    (hari_tanggal: "Senin, 17 Agt 2026", datang: "09:00", pulang: "17:00", kegiatan: "Video demo sistem inventaris; perbaikan masalah untuk dua aplikasi lainnya", paraf: ""),
    (hari_tanggal: "Selasa, 18 Agt 2026", datang: "09:00", pulang: "17:00", kegiatan: "Video demo untuk AI assisted research; video demo untuk AI meeting agent", paraf: ""),
    (hari_tanggal: "Rabu, 19 Agt 2026", datang: "09:00", pulang: "17:00", kegiatan: "Pembuatan PPT untuk presentasi akhir; perbaikan masalah aplikasi untuk video demo; video demo", paraf: ""),
    (hari_tanggal: "Kamis, 20 Agt 2026", datang: "09:00", pulang: "17:00", kegiatan: "Presentasi akhir", paraf: ""),
  ),
  rows: 39,
)
